### ISSUE TITLE
Agregar Reglas Oficiales

### ISSUE THREAD

**Issue by maria-o-makarova** [Technovation-Mexico/landing-page#2]
Agregar Reglas Oficiales all menú y crear la página con la traducción de las reglas:
https://docs.google.com/document/d/1Ub_F5-zF8SxnqtIfkl6dzKAvBWleFkNx8fCnpxcuLPw/edit?usp=sharing

**Comment by Laura021** [comment]
- Created as a new page .
- Add navigation link,
